---
name: 'Build docker images'
on:
  push:
    branches: ['main']
    paths:
      - '**.Dockerfile'
      - '.github/workflows/build-and-push.yml'
  schedule:
    - cron: '0 1 * * 0'

jobs:
  docker:
    name: 'Build and push'
    runs-on: 'ubuntu-22.04'
    strategy:
      matrix:
        include:
          - tag: 'almalinux-8'
            dockerfile: 'almalinux/8.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'almalinux-9'
            dockerfile: 'almalinux/9.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'almalinux-10'
            dockerfile: 'almalinux/10.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'amazonlinux-2'
            dockerfile: 'amazonlinux/2.Dockerfile'
            platforms: 'linux/amd64'

          - tag: 'amazonlinux-2023'
            dockerfile: 'amazonlinux/2023.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'centos-7'
            dockerfile: 'centos/7.Dockerfile'
            platforms: 'linux/amd64'

          - tag: 'debian-10'
            dockerfile: 'debian/10.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'debian-11'
            dockerfile: 'debian/11.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'debian-12'
            dockerfile: 'debian/12.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'debian-13'
            dockerfile: 'debian/13.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'fedora-39'
            dockerfile: 'fedora/39.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'fedora-40'
            dockerfile: 'fedora/40.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'fedora-41'
            dockerfile: 'fedora/41.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'fedora-42'
            dockerfile: 'fedora/42.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'fedora-43'
            dockerfile: 'fedora/43.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'opensuse-15.6'
            dockerfile: 'opensuse/15.6.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'opensuse-tumbleweed'
            dockerfile: 'opensuse/tumbleweed.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'rockylinux-8'
            dockerfile: 'rockylinux/8.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'rockylinux-9'
            dockerfile: 'rockylinux/9.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'rockylinux-10'
            dockerfile: 'rockylinux/10.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'ubuntu-18.04'
            dockerfile: 'ubuntu/18.04.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'ubuntu-20.04'
            dockerfile: 'ubuntu/20.04.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'ubuntu-22.04'
            dockerfile: 'ubuntu/22.04.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

          - tag: 'ubuntu-24.04'
            dockerfile: 'ubuntu/24.04.Dockerfile'
            platforms: 'linux/amd64,linux/arm64'

    steps:
      - name: 'Checkout the codebase'
        uses: 'actions/checkout@v4'

      - name: 'Set up QEMU'
        uses: 'docker/setup-qemu-action@v3'

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'

      - name: 'Login to DockerHub'
        if: ${{ github.event_name != 'pull_request' }}
        uses: 'docker/login-action@v3'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and push ${{ matrix.tag }}'
        uses: 'docker/build-push-action@v6'
        with:
          cache-from: 'type=gha,scope=${{ matrix.tag }}'
          cache-to: 'type=gha,scope=${{ matrix.tag }}'
          context: .
          file: '${{ matrix.dockerfile }}'
          platforms: '${{ matrix.platforms }}'
          push: ${{ github.event_name != 'pull_request' }}
          tags: '${{ github.repository }}:${{ matrix.tag }}'
