---
name: 'Build docker images'
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'centos-7'
            dockerfile: 'centos/7.Dockerfile'
            tags: 'antmelekhin/docker-systemd:centos-7'
          - name: 'debian-10'
            dockerfile: 'debian/10.Dockerfile'
            tags: 'antmelekhin/docker-systemd:debian-10'
          - name: 'debian-11'
            dockerfile: 'debian/11.Dockerfile'
            tags: 'antmelekhin/docker-systemd:debian-11'
          - name: 'debian-12'
            dockerfile: 'debian/12.Dockerfile'
            tags: 'antmelekhin/docker-systemd:debian-12'
          - name: 'ubuntu-20.04'
            dockerfile: 'ubuntu/20.04.Dockerfile'
            tags: 'antmelekhin/docker-systemd:ubuntu-20.04'
          - name: 'ubuntu-22.04'
            dockerfile: 'ubuntu/22.04.Dockerfile'
            tags: 'antmelekhin/docker-systemd:ubuntu-22.04'
          - name: 'rockylinux-8'
            dockerfile: 'rockylinux/8.Dockerfile'
            tags: 'antmelekhin/docker-systemd:rockylinux-8'
          - name: 'rockylinux-9'
            dockerfile: 'rockylinux/9.Dockerfile'
            tags: 'antmelekhin/docker-systemd:rockylinux-9'
          - name: 'amazonlinux-2023'
            dockerfile: 'amazonlinux/2023.Dockerfile'
            tags: 'antmelekhin/docker-systemd:amazonlinux-2023'

    steps:
      - name: 'Checkout the codebase'
        uses: actions/checkout@v3

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Login to DockerHub'
        uses: docker/login-action@v2
        with:
          username: 'antmelekhin'
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 'Build and push ${{ matrix.name }}'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.tags }}
