name: 'Update DockerHub Description'
on:
  push:
    branches: ['main']
    paths:
      - 'README.md'
      - '.github/workflows/dockerhub-description.yml'
jobs:
  dockerHubDescription:
    name: 'Update DockerHub Description'
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'Checkout the codebase'
        uses: 'actions/checkout@v4'

      - name: 'DockerHub Description'
        uses: 'peter-evans/dockerhub-description@v4'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
